name: Update Requirements Changes

on:
  push:
    paths:
      - 'docs/requirements/**'

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files from API
        id: changed-files
        uses: actions/github-script@v5
        with:
          script: |
            const payload = context.payload;
            const before = payload.before;
            const after = payload.after;
            const response = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: before,
              head: after
            });
    
            const files = response.data.files.map(file => file.filename);
            console.log("Changed Files:", files.join("\n")); // 콘솔에 변경된 파일 목록을 출력합니다.
            core.setOutput("list", files.join("\n")); // 출력 변수에 변경된 파일 목록을 설정합니다.
    