name: Update Requirements Changes

on:
  push:
    paths:
      - 'docs/requirements/**'

jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: files
        run: |
          echo "::set-output name=list::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})"
          
      - name: Use Changed Files
        run: |
          echo "Changed Files: ${{ steps.files.outputs.list }}"